'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import type { User } from '@scopeprofit/contracts';
import { api, ApiError, errorMessage } from '@/lib/api';
export default function Settings(){const router=useRouter();const[user,setUser]=useState<User|null>(null);const[key,setKey]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[saved,setSaved]=useState(false);
useEffect(()=>{api<User>('/auth/me').then(u=>{if(u.role!=='professional')router.replace('/dashboard');else setUser(u);}).catch(e=>{if(e instanceof ApiError&&e.status===401)router.replace('/login');else setError(errorMessage(e));});},[router]);
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setSaved(false);try{await api('/auth/ai-key',{method:'PUT',body:JSON.stringify({apiKey:key})});setKey('');setUser(u=>u?{...u,hasAiApiKey:true}:u);setSaved(true);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
return <main className="narrow page"><Link className="text-link" href="/dashboard">← Mis proyectos</Link><p className="eyebrow space-top">CONFIGURACIÓN</p><h1>Tu IA. Tu clave.</h1><p className="intro">ScopeProfit usa la clave de Gemini del propietario de cada proyecto. Conservás el control del consumo y los límites de tu cuenta.</p>{error&&<p role="alert" className="error">{error}</p>}{user?<section className="panel"><div className="panel-heading"><h2>Google Gemini</h2><span className="tag">{user.hasAiApiKey?'Clave configurada':'Sin configurar'}</span></div><form onSubmit={save}><label htmlFor="api-key">{user.hasAiApiKey?'Reemplazar clave API':'Clave API'}</label><input id="api-key" type="password" required minLength={10} maxLength={512} autoComplete="off" spellCheck={false} value={key} onChange={e=>setKey(e.target.value)} placeholder="Pegá tu clave de Google AI Studio"/><p className="small muted">Se cifra en el servidor. Nunca volvemos a mostrarla ni la guardamos en este navegador.</p><button className="button" disabled={busy}>{busy?'Guardando…':'Guardar clave segura'}</button>{saved&&<p role="status" className="success">Clave guardada. Ya podés retomar el relevamiento de tus proyectos.</p>}</form><p className="small muted">Los cargos o cuotas del proveedor corresponden a tu cuenta de Google. No compartas tu clave por el chat.</p></section>:<p role="status">Verificando acceso…</p>}</main>;}
